### ISSUE TITLE
[BUG] Windows-1252 encoding is not detected in turkish text

### ISSUE THREAD

**Issue by milahu** [jawah/charset_normalizer#407]
`charset_normalizer` returns `None`

```
$ chardetect star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt
star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt: Windows-1252 with confidence 0.73

$ file -i star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt
star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt: application/x-subrip; charset=iso-8859-1

$ python -c "import charset_normalizer; print(charset_normalizer.from_path('star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt').best())"
None
```

who is right? chardetect is right! the expected encoding is Windows-1252

`iso-8859-1` produces an ugly [<U+0085>](https://www.fileformat.info/info/unicode/char/85/index.htm) when piped to `less` (utf16 hex bytes)
or `c285` as utf8 hex bytes

[unicode-explorer.com/c/0085](https://unicode-explorer.com/c/0085)

> U+0085: The "Next Line" (NEL) control character was used in the 1970s for controlling printers and displays (e.g. VT100). Moves to the first position of the next line.

```diff
--- star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt.iso-8859-1
+++ star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt.Windows-1252
@@ -2242,7 +2242,7 @@
 
 505
 00:43:04,098 --> 00:43:05,428
-Adil davranmaktan bahsetmiþken<U+0085>
+Adil davranmaktan bahsetmiþken…
 
 506
 00:43:06,771 --> 00:43:09,777
```

## input file

`star_trek_tng_-_season_1_ep_03_-_the_naked_now.srt`

- [005093393.star.trek.the.next.generation.s01.e02.the.naked.now.(1987).tur.1cd.(5093393).zip](https://github.com/Ousret/charset_normalizer/files/13799054/005093393.star.trek.the.next.generation.s01.e02.the.naked.now.1987.tur.1cd.5093393.zip)
- https://www.opensubtitles.org/en/subtitles/5093393

**Comment by Ousret** [comment]
OK, noted. Will try to improve this case for the next minor.

**Comment by milahu** [comment]
> `Adil davranmaktan bahsetmiþken…`

it really is just that one byte that breaks charset_normalizer

```
$ printf '\x85' | iconv -f cp1254 -t utf8
…
```

when i remove that byte, the encoding `cp1254` is found

**Comment by Ousret** [comment]
We fixed that case. It will be available in the next release.
