### ISSUE TITLE
[DETECTION] utf_8_sig instead of utf_8

### ISSUE THREAD

**Issue by delins** [jawah/charset_normalizer#551]
`from_bytes` reports `utf_8` for data that starts with a UTF 8 BOM instead of `utf_8_sig`. It does however correctly identify the BOM, as it shows in the output when `explain=True` is given. While this may be the currently intended behavior, this creates the following issue:

```python
>>> data = b'\xEF\xBB\xBFtest'
>>> charset_normalizer.from_bytes(data).best()
<CharsetMatch 'utf_8' bytes(9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08)>
>>> data.decode('utf_8')
'\ufefftest'  # not what I wanted
>>> data.decode('utf_8_sig')
'test'  # this is what I wanted
```

Basically it forces users to know about and check for the BOM and then replace `utf_8` with `utf_8_sig` as the encoding argument to `decode`. Since text editors usually remove the BOM, users may be puzzled as to why their code fails but they don't see anything weird with their file until they open it in a hex editor.

**Comment by Ousret** [comment]
I can see how this can be confusing on first look.

Using the main API `charset_normalizer.from_bytes(data)` strip the UTF-8 SIG.

Consider this:

```python
from charset_normalizer import from_bytes, detect

if __name__ == "__main__":
    payload = b'\xEF\xBB\xBFtest'

    best_guess = from_bytes(
        payload,
        explain=True
    ).best()

    print(best_guess.encoding)  # output 'utf_8'
    print(best_guess)  # output 'test' correctly
    print(best_guess.bom)  # output True

    # now using the legacy 'detect' function
    print(detect(payload))  # {"encoding": "UTF-8-SIG",...}
```

UTF-8-SIG isn't really "standard" but only "enough" used to be recognized.

regards,

**Comment by delins** [comment]
Thanks for the answer. `UTF-8-SIG` as a codec indeed seems a Python thing only.
