### ISSUE TITLE
compare performance to cchardet

### ISSUE THREAD

**Issue by milahu** [jawah/charset_normalizer#566]
currently the readme compares performance
only to chardet, but not to cchardet

same for [bin/performance.py](https://github.com/jawah/charset_normalizer/raw/master/bin/performance.py)

performance-sensitive users prefer cchardet
so the comparison to chardet is misleading

charset_normalizer says:
charset_normalizer is 20x faster than chardet

[rs_chardet](https://github.com/emattiza/rs_chardet) says:
cchardet is 40x faster than rs_chardet
cchardet is 4000x faster than chardet
&rarr; cchardet is 200x faster than charset_normalizer

https://github.com/jawah/charset_normalizer/issues/182#issue-1221074881 says:
cchardet is 5x faster than charset_normalizer

anyway, both are useful:
cchardet works better on small inputs
charset_normalizer works better on large inputs (#486)

cchardet:
https://github.com/PyYoshi/cChardet
https://github.com/faust-streaming/cChardet

**Comment by Ousret** [comment]
> [rs_chardet](https://github.com/emattiza/rs_chardet) says:
cchardet is 40x faster than rs_chardet
cchardet is 4000x faster than chardet
→ cchardet is 200x faster than charset_normalizer

It does not seems right. Either the project do wrong or I missed something. chardetng is really much faster than what is presented. It is simply not possible. (chardet 	v5.1.0 	0.20407073211428026; rs_chardet 	v0.1.1 	25.446704726774133)
They use a single (file) sample to measure performances[...] We have 400+ samples. (And I consider it to be the absolute minimum).

> cchardet works better on small inputs
charset_normalizer works better on large inputs

That seems like an over simplification of what is said. Sometime cchardet fail on small input and sometime charset-normalizer succeed where cchardet fail.

> performance-sensitive users prefer cchardet
so the comparison to chardet is misleading

Where did I say something "misleading"? When charset-normalizer came, it was to propose an alternative to Chardet that was dominant at the time. Comparing pure C++ with Python isn't helping too. We already mention cchardet anyway for transparency.

Moreover, you can exponentially improve perf by simply disabling the support for 60 extra encodings, it will go a lot faster.
If you wanted to truly compare, apple-to-apple. I don't think anyone realize how they would perform with our 99 encodings support. It WILL be catastrophic.

> cchardet:
https://github.com/PyYoshi/cChardet
https://github.com/faust-streaming/cChardet

To my eyes, they are both unmaintained. The first is long dead, the second gave up.

Regards,
